package constants

const (
	PROMOTYPEBUYXGETY   = "BUY_X_GET_Y_FREE"
	PROMOTYPEPERCENTAGE = "PERCENTAGE_DISCOUNT"

	PROMOSEGMENTATIONCITY      = "CITY"
	PROMOSEGMENTATIONLOYALUSER = "LOYAL_USER"
	PROMOSEGMENTATIONNEWUSER   = "NEW_USER"
	PROMOSEGMENTATIONALL       = "ALL"
)
