// Code generated by MockGen. DO NOT EDIT.
// Source: ./order_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "hangry/domain/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// GetUserOrderCount mocks base method.
func (m *MockOrderRepository) GetUserOrderCount(ctx context.Context, tx *gorm.DB, userID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrderCount", ctx, tx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrderCount indicates an expected call of GetUserOrderCount.
func (mr *MockOrderRepositoryMockRecorder) GetUserOrderCount(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrderCount", reflect.TypeOf((*MockOrderRepository)(nil).GetUserOrderCount), ctx, tx, userID)
}

// MakeOrder mocks base method.
func (m *MockOrderRepository) MakeOrder(ctx context.Context, tx *gorm.DB, order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrder", ctx, tx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeOrder indicates an expected call of MakeOrder.
func (mr *MockOrderRepositoryMockRecorder) MakeOrder(ctx, tx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrder", reflect.TypeOf((*MockOrderRepository)(nil).MakeOrder), ctx, tx, order)
}
